### ISSUE TITLE
Move docker image to org account

### ISSUE THREAD

**Issue by moshloop** [vmware/kube-fluentd-operator#101]
Artefacts shouldn't be hosted in an individuals account if the repo is owned by the org. 

If using a vmware docker account is problematic, using the github docker registry with github actions might be a good alternative.

**Comment by carpenterm** [comment]
Thank you for the suggestion, we are aware of this issue and will be working to correct it for the next release.

**Comment by dimalbaby** [comment]
We have addressed this issue and moved to vmware account

Thanks,
Dimal
