### ISSUE TITLE
Outdated fluent-plugin-kubernetes plugin causing parsing issues

### ISSUE THREAD

**Issue by raja-gola** [vmware/kube-fluentd-operator#108]
`fluent-plugin-kubernetes` plugin is outdated with it's last commit in 2015 and is causing below issue. Also `fluent-plugin-kubernetes_metadata_filter` does the job of adding k8s metatdata for us, can this plugin be removed.

Below config in `config-reloader/templates/kubernetes-postprocess.conf` causes the issue

```
# Parse logs in the kube-system namespace using the kubernetes formatter.
<filter kube.kube-system.**>
  @type parser
  reserve_data true
  key_name log
  emit_invalid_record_to_error false
  <parse>
    @type kubernetes
    time_format %FT%T%:z
  </parse>
</filter>
```

Issue explained: 

Consider log event as below:

```
2020-03-28T06:14:20+00:00	kube.kube-system.kube-apiserver-master001.kube-apiserver	{"log":"I0328 06:14:20.300747       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.system.antrea.tanzu.vmware.com\n","stream":"stderr","docker":{"container_id":"986e1e7b2947a77b439ff19cea994512d15dd96321b17d33b6892de9a1804985"},"kubernetes":{"container_name":"kube-apiserver","namespace_name":"kube-system","pod_name":"kube-apiserver-master001","container_image":"xx.xx.xx/vmware/tanzu-kubernetes-grid/kube-apiserver:v1.16.3_vmware.1","container_image_id":"docker-pullable://xx.xx.xx/vmware/tanzu-kubernetes-grid/kube-apiserver@sha256:297f4881c9597bd56a1bb90691e5af7497754b60e4891bf411c2d4114e399d6f","pod_id":"51f2e745-5967-4ec2-a068-a8d4f4b643f4","host":"master001","labels":{"component":"kube-apiserver","tier":"control-plane"}},"container_info":"986e1e7b2947a77b439ff19cea994512d15dd96321b17d33b6892de9a1804985-stderr","severity":"I","pid":"1","source":"controller.go:107","message":"OpenAPI AggregationController: Processing item v1beta1.system.antrea.tanzu.vmware.com\n"}
```

When the above filter config is applied, it basically transforms the log into following
```
"log": {"2020-03-28T06:14:20+00:00	kube.kube-system.kube-apiserver-master001.kube-apiserver	{"log":"I0328 06:14:20.300747       1 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.system.antrea.tanzu.vmware.com\n","stream":"stderr","docker":{"container_id":"986e1e7b2947a77b439ff19cea994512d15dd96321b17d33b6892de9a1804985"},"kubernetes":{"container_name":"kube-apiserver","namespace_name":"kube-system","pod_name":"kube-apiserver-master001","container_image":"xx.xx.xx/vmware/tanzu-kubernetes-grid/kube-apiserver:v1.16.3_vmware.1","container_image_id":"docker-pullable:/xx.xx.xx/vmware/tanzu-kubernetes-grid/kube-apiserver@sha256:297f4881c9597bd56a1bb90691e5af7497754b60e4891bf411c2d4114e399d6f","pod_id":"51f2e745-5967-4ec2-a068-a8d4f4b643f4","host":"master001","labels":{"component":"kube-apiserver","tier":"control-plane"}},"container_info":"986e1e7b2947a77b439ff19cea994512d15dd96321b17d33b6892de9a1804985-stderr","severity":"I","pid":"1","source":"controller.go:107","message":"OpenAPI AggregationController: Processing item v1beta1.system.antrea.tanzu.vmware.com\n"}
"}
```
Thus, it will not enable plugin like `fluent-plugin-vmware-loginsight` to extract metadata from log and it becomes very difficult to search LogInsight logs with this metadata.

**Comment by raja-gola** [comment]
Even below config needs an update. From fluentd contianer logs.

```
2020-04-01 02:42:31 +0000 [warn]: parameter 'merge_json_log' in <filter kubernetes.**>
  @type kubernetes_metadata
  merge_json_log true
  preserve_json_log true
</filter> is not used.
2020-04-01 02:42:31 +0000 [warn]: parameter 'preserve_json_log' in <filter kubernetes.**>
  @type kubernetes_metadata
  merge_json_log true
  preserve_json_log true
</filter> is not used.
```

**Comment by dimalbaby** [comment]
> `fluent-plugin-kubernetes` plugin is outdated with it's last commit in 2015 and is causing below issue. Also `fluent-plugin-kubernetes_metadata_filter` does the job of adding k8s metatdata for us, can this plugin be removed.
> 
> Below config in `config-reloader/templates/kubernetes-postprocess.conf` causes the issue
> 
> ```
> # Parse logs in the kube-system namespace using the kubernetes formatter.
> <filter kube.kube-system.**>
>   @type parser
>   reserve_data true
>   key_name log
>   emit_invalid_record_to_error false
>   <parse>
>     @type kubernetes
>     time_format %FT%T%:z
>   </parse>
> </filter>
> ```

@raja-gola,  '@type kubernetes' is not from the outdated fluent-plugin-kubernetes plugin. This is a custom parse plugin loaded from /etc/fluent/plugin directory. We are using fluent-plugin-kubernetes_metadata_filter plugin for getting the k8s meta. 
I agree with your second point. I think these  merge_json_log, preserve_json_log parameters are removed as per https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter. Thanks for pointing the issue

**Comment by Cryptophobia** [comment]
This seems to be partially addressed in https://github.com/vmware/kube-fluentd-operator/pull/115  by removing the extra merge_json and preserve_json parameters.
