### ISSUE TITLE
Reloader seems to not retry after failure with outputs

### ISSUE THREAD

**Issue by rtfpessoa** [vmware/kube-fluentd-operator#119]
After using this operator with s3 output.
If s3 is not available immediatly when the reloader starts it will never work.
Seems like it could restart or just fail and let k8s handle the restarts.

Basically if I restart the pods they start working.

Any ideas on how imporve.fix this behaviour?

**Comment by dimalbaby** [comment]
@rtfpessoa Thank you reporting the issue. Did you get a chance to try with the latest fluentd-operator https://github.com/vmware/kube-fluentd-operator/releases/tag/v1.12.0 ?
Are you setting the  parameter`  --interval=60` ?

**Comment by rtfpessoa** [comment]
We did some changes like using `check_apikey_on_start`, `check_bucket` and `retry_forever` in the s3 plugin and seems like it is better.
Possibly not a problem of the operator then.
Thank you
