### ISSUE TITLE
Slack plugin support

### ISSUE THREAD

**Issue by sneko** [vmware/kube-fluentd-operator#12]
Hi :)

What do you think about supporting the Slack plugin? Is it legitimate for this fluentd operator?

https://github.com/sowawa/fluent-plugin-slack

Thanks

**Comment by sneko** [comment]
In fact I'm not even sure if it's what I should do...

I would like to be notified of errors of my whole cluster and finally I'm thinking that it may be better if my ElasticSearch cluster was pushing notifications to Slack instead of Fluentd.

Do you have any advice to provide about that please 😃 ?

**Comment by jvassev** [comment]
Hi,

While it's easy to add any plugin to the base image, I'd suggest to push any analytics up the stack. Fluentd and this project itself should be considered just a transport/pre-processing layer.

Imagine tomorrow you need to react on events coming from another source - you'd need to configure notifications there too. Instead, manage the notifications/alarms centrally at the ELK layer :)

**Comment by sneko** [comment]
Thank you I will look into that 😀
