### ISSUE TITLE
High CPU usage on fluentd pods and Kubernetes API server

### ISSUE THREAD

**Issue by carpenterm** [vmware/kube-fluentd-operator#121]
Lately we have seen a large increase in CPU usage on the Kubernetes API server and kube-fluentd-operator pods. Restarting either the API server or KFO causes the CPU to drop but then it picks backup again after 30-40 mins.

Recent testing has isolated the issue to the kubernetes metadata filter plugin - more info can be found here https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/224 

Downgrading to 2.4.1 fixes the issue, we should pin this plugin until the above bug is resolved.

**Comment by kkapoor1987** [comment]
@carpenterm @dimalbaby If no one is working on this I can send the PR for to pin the version to 2.4.1?

**Comment by clearascloud** [comment]
> @carpenterm @dimalbaby If no one is working on this I can send the PR for to pin the version to 2.4.1?

Hey, we are working on this its in our labs And appears successful in reducing CPU, we can cut a new release with this fix, hopefully pretty soon. Thanks !

**Comment by kkapoor1987** [comment]
@tjorourke Would recommend us to run custom image for now with 2.4.1 plugin version ?

**Comment by tjorourke** [comment]
> @tjorourke @carpenterm Would recommend us to run custom image for now with 2.4.1 plugin version ?

Yes we have seen this resolves it, we are still working on some other issues and will vut a build as soon as we can. cc @dimalbaby

**Comment by kkapoor1987** [comment]
@tjorourke  thanks for the reply. We can run the custom image for little while

**Comment by dimalbaby** [comment]
The issue got fixed with the above MR
