### ISSUE TITLE
Migrate to official splunk plugin GEM 

### ISSUE THREAD

**Issue by kkapoor1987** [vmware/kube-fluentd-operator#125]
In our testing, we found that the current Splunk plugin is not officially supported by Splunk and the maintainer is not actively working on it. 

I would like to propose to migrate to the official Splunk plugin 
https://github.com/splunk/fluent-plugin-splunk-hec

I am more than happy to submit the PR for the same.
@dimalbaby Thoughts ?

**Comment by herikwebb** [comment]
Was a bit confused on this one as well when trying to use `@splunk_hec` per the official splunk plugin docs instead of `@splunkhec`, I also think that it would be nice to have official splunk plugin included instead.
