### ISSUE TITLE
Metrics by namespace

### ISSUE THREAD

**Issue by mg03** [vmware/kube-fluentd-operator#126]
Hi

I am curious to know if I can get metrics by namespace. For example, how many log lines or bytes are generated from workloads in a namespace?

Any example/s would be greatly appreciated on how to achieve the above

Regards

Meher

**Comment by Cryptophobia** [comment]
@mg03 , you can expose custom metrics via the prometheus gem and use prometheus to capture the metrics. Detailed write up here:

https://docs.fluentd.org/monitoring-fluentd/monitoring-prometheus

Per namespace, you would have to probably write a custom prometheus formater to format metrics per namespace.

**Comment by Cryptophobia** [comment]
Closing this one for now as it's not really in the scope of the main project. If someone wants to contribute an output plugin that formats metrics per namespace and exposes via prometheus gem, it would be great contribution!
