### ISSUE TITLE
Deployment rather than daemonset for Fluentd for scenarios where you have a broker in between. 

### ISSUE THREAD

**Issue by johnpemberton** [vmware/kube-fluentd-operator#127]
Appreciate this may be a little bit niche and possibly outside the scope of this project, but we're currently looking at a logging architecture whereby we run a fluentbit deamonset, who's responsibility is to ship logs off nodes as quickly as possible to a broker like kafka.  We would then run a fluentd deployment, who's responsibility is to read from kafka, parse the logs and route to the respective backends, whether they be elasticsearch, datadog, newrelic etc.   I think putting a broker in there is a common pattern to cope with spiky log traffic.

Is there any scope for this project to support that kind of pattern?  

Love this operator btw.   Makes it very easy to enable multitenant logging solutions.

**Comment by Cryptophobia** [comment]
I'm am pretty sure this is outside the scope right now. In your example, KFO is a direct replacement for fluentbit daemonset.

Easiest way that could be achieved is to deploy KFO with another deployment for example an (fluentd+kafka-plugin) image to read from the broker and ship the logs to the respective backends.
