### ISSUE TITLE
Helm chart v0.3.4 is not availalbe at url https://github.com/vmware/kube-fluentd-operator/releases/download/v1.12.0/log-router-0.3.4.tgz

### ISSUE THREAD

**Issue by a-b-v** [vmware/kube-fluentd-operator#143]
Helm chart v0.3.4 is not availalbe at url https://github.com/vmware/kube-fluentd-operator/releases/download/v1.12.0/log-router-0.3.4.tgz

**Comment by dimalbaby** [comment]
@a-b-v There is no v0.3.4 available for v1.12.0 release. You can find the Helm charts per releases https://github.com/vmware/kube-fluentd-operator/releases
