### ISSUE TITLE
The reloader raise an error then admin-namespace defined

### ISSUE THREAD

**Issue by a-b-v** [vmware/kube-fluentd-operator#145]
Reloader pod manifest:
  - command:
    - /bin/config-reloader
    - --datasource=default
    - --default-configmap=fluentd-config
    - --interval=45
    - --log-level=info
    - --output-dir=/fluentd/etc
    - --templates-dir=/templates
    - --id=kfo-log-router
    - --fluentd-binary
    - /usr/local/bundle/bin/fluentd -p /fluentd/plugins
    - --kubelet-root
    - /var/lib/kubelet
    - --meta-key=metadata
    - --meta-values=cluster=the_kube,
    - --admin-namespace=kube-system

-------------------
Error:

level=fatal msg="flag parsing error: unknown long flag '--admin-namespace'"

**Comment by dimalbaby** [comment]
@a-b-v Can you share more details ? Which version are you using? Looks like you are using a different version again the latest chart ?

**Comment by a-b-v** [comment]
Yes, i used the --set image.tag=v1.12.0, according to outdated readme. Thanks.

**Comment by a-b-v** [comment]
Documentation refreshed
