### ISSUE TITLE
Helm chart doesnt support adding annotations to service Account 

### ISSUE THREAD

**Issue by kkapoor1987** [vmware/kube-fluentd-operator#160]
We are using this project to deploy kube-fluentd-operator using provided helm chart in eks cluster. In order to use to sent logs to Cloudwatch securely, we have to annotate ServiceAccount with IAM role to liverage IRSA feature from AWS. 

I would be more than happy to add support for annotation in helm chart if we can merge it to master

**Comment by Cryptophobia** [comment]
This is closed by https://github.com/vmware/kube-fluentd-operator/pull/167
