### ISSUE TITLE
No solution to configure the log level of the vmware/kube-fluentd-operator

### ISSUE THREAD

**Issue by ls-julien-deruere** [vmware/kube-fluentd-operator#181]
I'm using the Helm chart, the logLevel only apply to the config-reloader.
But the Fluentd container has no way to configure the log level.

I end up having a lot of noise:
` level=debug msg="Using default configmap name ('fluentd-config') for namespace 'kube-system'"`

**Comment by Cryptophobia** [comment]
Yes, config-reloader has it's own log-level that is independently configured outside of fluentd. As config-reloader is written in Go and verifies/reloads the configs for fluentd.

Have you tried setting the `log-level` field in your fluentd.conf file: https://github.com/vmware/kube-fluentd-operator/blob/master/config-reloader/templates/fluent.conf#L4

This can be done through the configMap that fluent-operator uses: https://github.com/vmware/kube-fluentd-operator/blob/master/config-reloader/examples/manifests/kfo-test.yaml#L142

Possible values are: `Specifies the log level e.g. trace, debug, info, warn, error, or fatal` (https://docs.fluentd.org/deployment/system-config)

**Comment by Cryptophobia** [comment]
Edit: Sorry, yes. We can figure out a quick way to propogate log-level in the generator.go code: https://github.com/vmware/kube-fluentd-operator/blob/master/config-reloader/generator/generator.go

**Comment by ls-julien-deruere** [comment]
Yes that would be nice to propagate the log-level to both containers 👍

**Comment by kkapoor1987** [comment]
@Cryptophobia  I was thinking to implement it. I have question should we have separate log level for fluentd or can we use same one which is provided for reloader?

**Comment by Cryptophobia** [comment]
@kkapoor1987 , I think ideally we can have two environment flags: `logLevel` and `fluentdLogLevel` since they are two separate containers. If `fluentdLogLevel` is not set, `fluentdLogLevel` should default to what is set for `logLevel`. That way we can have complete control of each of the log levels, there is a safe default fallback, and it will be backwards compatible in case `fluentdLogLevel` is not set or user is deploying with old helm chart version.

**Comment by kkapoor1987** [comment]
@Cryptophobia  I started working on something on those lines only. Will share the update sometime this week.

**Comment by Cryptophobia** [comment]
Awesome @kkapoor1987 !

**Comment by Cryptophobia** [comment]
Hey @kkapoor1987 , how's it coming along? Would love to include this one in the upcoming latest release.

**Comment by kkapoor1987** [comment]
@Cryptophobia  Apology for late reply ... Let me know if you have any feedback for the PR.

**Comment by Cryptophobia** [comment]
closed by https://github.com/vmware/kube-fluentd-operator/pull/196 . Thank you @kkapoor1987
