### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by jliao2011** [vmware/kube-fluentd-operator#182]
Just wondering what your guys' release cadence is, we would like to switch to the official splunk hec plugin asap.

**Comment by kkapoor1987** [comment]
We have the same requirement. It would be great to have a new release

**Comment by Cryptophobia** [comment]
We targeting to make a new release soon within the next 2 weeks. We have encountered some restrictions on public DockerHub (effective Nov 20) that we need to work through.

We are looking forward to this release as much as everyone else! 🙏 🙂

**Comment by Cryptophobia** [comment]
@jliao2011 @kkapoor1987 

Changelog of the pre-release is here: https://github.com/vmware/kube-fluentd-operator/releases/tag/v1.14.0-beta.2

Image is live on docker hub with `latest` and `v1.14.0-beta.2` tags:
https://hub.docker.com/r/vmware/kube-fluentd-operator

Please report any issues here and we will address them and patch if necessary. Next major release we will do in a few weeks.
