### ISSUE TITLE
buffer path mandated to /var/log

### ISSUE THREAD

**Issue by karthiknagraj** [vmware/kube-fluentd-operator#183]
Hi, 
Currently makeSafeBufferPath() which is present in [destination.go](https://github.com/vmware/kube-fluentd-operator/blob/master/config-reloader/processors/destinations.go) mandates buffer to be at path /var/log. Even if we provide specific buffer path under \<buffer\> tag, it is used as a hash value and gets appended at the end for the creation of **.buf**.

`func makeSafeBufferPath(ctx *ProcessorContext, origBufPath string) string {
	return fmt.Sprintf("/var/log/kfo-%s-%s-%s.buf", util.MakeFluentdSafeName(ctx.DeploymentID), ctx.Namepsace, util.Hash("", origBufPath))
}`

Is there any plans of adding this enhancement to allow to change the buffer path ?

**Comment by Cryptophobia** [comment]
@karthiknagraj, What do you want to change the base path to ? What is the particular use-case?

This is the internal buffer created for each buffer of each processor of a namespace. We could make it fully overwritable and default to the current way of setting it, but I am a little worried it might have other security implications. And having this overwritable could also create a single-point of failures ... At a minimum, this base buffer path would need to be validated and errors thrown when validation fails.

We are open to PRs.

**Comment by karthiknagraj** [comment]
@Cryptophobia, I want to change the base path to, let's say /var/log/fluentd. Currently we have a very large traffic flowing through fluentd to elasticsearch. During the downtime of elasticsearch, /var/log gets filled up quickly( as this partition has lesser space). For this reason we have created a new partition with larger capacity. Now we want internal buffer created for each processor of a namespace to point to the new path.

**Comment by Cryptophobia** [comment]
@karthiknagraj , so you are mounting a new volume partition on the path `/var/log/fluentd` for the processor's buffers?

So it sounds like we can just make a `bufferMountFolder` which can be appended at the end of `/var/log/{$bufferMountFolder} like so? Would that solve the problem you are having?

**Comment by karthiknagraj** [comment]
Sorry for the late reply. Yes, the bufferMountFolder variable should work for us. We are using a openstack based on-prem deployment and disk space is very limited.

**Comment by Cryptophobia** [comment]
@karthiknagraj, this has been merged in #206 and will make the next minor release with new chart version.

**Comment by karthiknagraj** [comment]
Thanks @Cryptophobia
