### ISSUE TITLE
bad label name

### ISSUE THREAD

**Issue by a-b-v** [vmware/kube-fluentd-operator#198]
Hello everyone!

This config:

    <match **>
      @type relabel
      @label dddddd
    </match>

    <label @dddddd>
      <match **>
         @type elasticsearch
         #       include_tag_key true
         host "#{ENV['ingress_elk_host']}"
         user "#{ENV['ingress_elk_user']}"
         password "#{ENV['ingress_elk_password']}"
         scheme "https"
         ssl_verify "false"
         ssl_version TLSv1_2
         port "9260"
         logstash_format true
         reload_connections "true"
         logstash_prefix "nginx-ingress"
         buffer_chunk_limit 1M
         buffer_queue_limit 32
         flush_interval 1s
         max_retry_wait 30
         disable_retry_limit
         num_threads 8
      </match>
    </label>

shows error: time="2021-04-13T13:17:26Z" level=info msg="Configuration for namespace ingress-nginx cannot be validated: bad label name: dddddd"

What i do wrong?

**Comment by Cryptophobia** [comment]
@a-b-v , can you try setting a `@` character in front of the name of the label in the top match config. Like this:

```
<match **>
  @type relabel
  @label @dddddd
</match>
```

**Comment by a-b-v** [comment]
> @a-b-v , can you try setting a `@` character in front of the name of the label in the top match config. Like this:
> 
> ```
> <match **>
>   @type relabel
>   @label @dddddd
> </match>
> ```
> 
> That is the official syntax to support define label at the top. Let me know if that fixes your issue. It passes validation of the config when I test.

Thanks, it works. One need to update the example in readme.
