### ISSUE TITLE
Some logs of the router should be display into stdout, no?

### ISSUE THREAD

**Issue by sneko** [vmware/kube-fluentd-operator#24]
Hi!

I'm trying to set some alerts from my ElasticSearch cluster when something happens on the stderr stream.

I just noticed that your Fluentd routers were writing on this stream for this kind of message:
```
{
  "_index": "xxxxxxx:2018.08.09",
  "_type": "fluentd",
  "_id": "zjHEIGUBfMVtb4xVhlCo",
  "_version": 1,
  "_score": null,
  "_source": {
    "log": "time=\"2018-08-09T22:17:45Z\" level=debug msg=\"Will not process namespace 'monitoring': configmaps \\\"fluentd-config\\\" not found\"\n",
    "stream": "stderr",
    "docker": {
      "container_id": "aa13f4ee0ccdaf70b7b3e0cd247caf27ae41618ae3e60970f1c91eec3d014878"
    },
    "kubernetes": {
      "container_name": "reloader",
      "namespace_name": "logging",
      "pod_name": "fluentd-log-router-qsd54",
      "container_image": "jvassev/kube-fluentd-operator:latest",
      "container_image_id": "docker-pullable://jvassev/kube-fluentd-operator@sha256:684d41b219573d27d7029ab3a031beb63c92f412aa7520134086f0e2a03d64e8",
      "pod_id": "3b32f90e-9c1a-11e8-9255-42010a800003",
      "labels": {
        "app": "log-router",
        "release": "fluentd"
      },
      "host": "XXXXXXXXXXXX"
    },
    "container_info": "aa13f4ee0ccdaf70b7b3e0cd247caf27ae41618ae3e60970f1c91eec3d014878-stderr",
    "@timestamp": "2018-08-09T22:17:45.692996268+00:00"
  },
  "fields": {
    "@timestamp": [
      "2018-08-09T22:17:45.692Z"
    ]
  },
  "highlight": {
    "stream": [
      "@kibana-highlighted-field@stderr@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1533853065692
  ]
}
```

Indeed the router considers it as "debug" so I guess it should go to the stdout stream, what are your thoughts?

Thanks!

**Comment by sneko** [comment]
I set my "logLevel" to "info" in the chart but there is still remaining logs onto the stderr:
```
time="2018-08-09T22:53:36Z" level=info msg="Running main control loop"
```

So I guess all router logs are written to stderr 😄

**Comment by jvassev** [comment]
Yes, all logs from the `config-reloader` go to stderr. Currently there is no way to change this (some apps let you chose stderr or stdout as you noticed).

Well, I think it would be hard to come with a regex or rule that detects problems in all apps. 
Instead try to be more specific and define a different rule for the different `kubernetes.labels.app` values.

For the the `log-router` app label you can catch misconfigured namespaces looking for specific strings in the `message` field. Just totally ignore the `stream`.

**Comment by sneko** [comment]
Yeah I think at first I will catch "error" word in messages and gradually implement more precise regexp depending on the app the log comes from.

Thank you @jvassev for your answer! It helps me to take a decision 😀
