### ISSUE TITLE
logage vs logRotate?

### ISSUE THREAD

**Issue by SuitableProduce** [vmware/kube-fluentd-operator#241]
What is the difference between these two settings?  

Maybe some more documentation on how the log rotate works?  I think `logage` is from previous versions, while `logRotate` is the same thing, just in newer versions.  

Is this executing a `find` on the fluentd log dir, and deleting things that meet either the `logRotateSize` or `logRotateAge` values under the `logRotate` section of the `values.yaml`?  

If you have `logRotate` enabled, at what time does it happen?

**Comment by Cryptophobia** [comment]
You can read more in the fluentd official documentation. We do not do anything custom, just set the command arg flags on fluentd start up.

https://docs.fluentd.org/deployment/logging#log-rotation-setting
