### ISSUE TITLE
[error]: Failed to reload config file: expected end of line at systemd.conf line 8,12

### ISSUE THREAD

**Issue by alex-vmw** [vmware/kube-fluentd-operator#266]
Hello. After upgrade from v1.15.1 to v1.15.3 we have seen a number of the below errors in the fluentd logs:
```
2021-10-05 13:35:33 +0000 [error]: Failed to reload config file: expected end of line at systemd.conf line 8,12
  7:   @id in_systemd_kubelet
  8:   matches [{ "_SYSTEMD_UNIT": "kubelet.service" }]

     ------------^
  9:   <storage>
```

Here is the full log file:
[kube-fluentd-operator-d85b4.log.gz](https://github.com/vmware/kube-fluentd-operator/files/7296750/kube-fluentd-operator-d85b4.log.gz)

**Comment by alex-vmw** [comment]
This error was root caused as an issue with the splunkhec plugin. I think KFO should completely remove Splunk support for now by removing splunk-hec and splunkhec plugins until these tickets below are fixed:
https://github.com/splunk/fluent-plugin-splunk-hec/issues/187
https://github.com/fluent/fluentd/issues/3530 or https://github.com/cmeerbeek/fluent-plugin-splunkhec/issues/27

**Comment by xelalexv** [comment]
Issue https://github.com/splunk/fluent-plugin-splunk-hec/issues/187 has been fixed with [release v1.2.10](https://github.com/splunk/fluent-plugin-splunk-hec/releases/tag/1.2.10). Would it be possible to remove the deprecation for this plugin and include it again?

**Comment by javiercri** [comment]
Hello. Sure we can work on it!

**Comment by xelalexv** [comment]
That would be great!

BTW, I've built my own image based on the latest KFO image, in which I re-added the 1.2.10 release of the plugin. Everything is working, config reload is not causing any trouble.
