### ISSUE TITLE
[in_tail_container_logs] invalid time format

### ISSUE THREAD

**Issue by ws-prive** [vmware/kube-fluentd-operator#290]
Hi,

I have installed this chart with:
```
# https://github.com/vmware/kube-fluentd-operator
VERSION_RELEASE=1.16.1
# https://github.com/vmware/kube-fluentd-operator/blob/master/charts/log-router/Chart.yaml
VERSION_LOGROUTER=0.4.0

CLUSTER_NAME=k8s-test
NAMESPACE=logging
NAMESPACE_FOR_LOGGING=kube-system

CHART_URL="https://github.com/vmware/kube-fluentd-operator/releases/download/v${VERSION_RELEASE}/log-router-${VERSION_LOGROUTER}.tgz"

helm upgrade kube-fluentd-operator ${CHART_URL} \
  --install \
  --create-namespace \
  --namespace=${NAMESPACE} \
  --set rbac.create=true \
  --set meta.key=cluster_info \
  --set meta.values.clustername=${CLUSTER_NAME} \
  --set image.tag=v${VERSION_RELEASE} \
  --set image.repository=vmware/kube-fluentd-operator
```

I have used this fluent.conf:
```
<match **>
  @type logzio_buffered
  endpoint_url https://listener.logz.io:8071?token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=my_type
  output_include_time true
  output_include_tags true
  http_idle_timeout 10
  <buffer>
      @type memory
      flush_thread_count 4
      flush_interval 3s
      chunk_limit_size 16m
      queue_limit_length 4096
  </buffer>
</match>
```

I do see a lot of these entries in the logs:
```
[in_tail_container_logs] invalid time format: value = 2021-11-19T10:00:00.379802187+01:00, error_class = ArgumentError, error = string doesn't match
```
How can I resolve this?

Thanks!

**Comment by Cryptophobia** [comment]
@ws-prive , this was fixed in #291 . There was a basic format for regex matching that caused this issue. I have reverted back to using the extended datetime parser regex format. What container runtime do you use by the way?

**Comment by ws-prive** [comment]
Hi @Cryptophobia,

Thanks, I am using containerd.

**Comment by Cryptophobia** [comment]
@ws-prive , good to know. We use docker and probably the reason we haven't seen this issue since the change to v1.16.1 . By the way, what cloud provider do you use for the k8s cluster? 

Maybe that influences the timestamp format as well since your timestamps have the UTC timezone offset.

**Comment by Cryptophobia** [comment]
This will be fixed in upcoming release v1.16.2

**Comment by ws-prive** [comment]
Hi @Cryptophobia ,

Thanks, any idea when 1.16.2 is going to be released?  I am running this on a vm, local on my laptop, so bare-metal install
.

**Comment by Cryptophobia** [comment]
@ws-prive , 1-2 days. There are 2 more issues that need to fixed and tested before then. You can press the Watch button above and subscribe to the Release notifications. You will get notification on when the new tag is made and the docker container will be there in a few mins after that.

**Comment by ws-prive** [comment]
@Cryptophobia

Thanks!

**Comment by Cryptophobia** [comment]
@ws-prive , New `v1.16.2` release is out. New image is now `docker.io/vmware/kube-fluentd-operator:v1.16.2`

**Comment by ws-prive** [comment]
@Cryptophobia, thanks for the update!

**Comment by ws-prive** [comment]
Hi @Cryptophobia,

Seems to be working, thanks. Are there anywhere (better) examples how to use the CRD's instead of the configmap?

**Comment by Cryptophobia** [comment]
Hi @ws-prive , going forward should prefer to migrate to CRDs. Have you read the CRD section in the docs here? https://github.com/vmware/kube-fluentd-operator#custom-resource-definitioncrd-support-since-v1130

If you have many fluentd configmaps, then it would be wise to deploy config-reloader with the flag `--crd-migration-mode` (https://github.com/vmware/kube-fluentd-operator#synopsis) . This will allow you to use both crd and configmaps at the same time. Once all the configmaps are migrated to the crds, then you can disable `--crd-migration-mode` and switch from `--set datasource=default` to permanently using `--set datasource=crd` when deploying with helm.

After the above migration mode (when you can use both crd and configmaps), the only thing required is for you to run KFO with the `helm upgrade kfo --set datasource=crd` in values.yaml of the helm release going forward.

Configmap and CRDs are pretty much identical:

```
apiVersion: logs.vdp.vmware.com/v1beta1
kind: FluentdConfig
metadata:
  name: fd-config
  namespace: default
spec:
  fluentconf: |
    <source>
       @type mounted-file
       # need to specify the path on the container filesystem
       path /var/log/hello.log
       labels app=hello-logger
    </source>
    <match **>
       @type cloudwatch_logs
       auto_create_stream true
       log_stream_name_key stream_name
       remove_log_stream_name_key true
       retention_in_days 90
       region "us-east-1"
       <buffer>
         @type file
         path /var/log/fluentd
         flush_interval 5s
         flush_thread_count 8
         chunk_limit_size 2m
         queued_chunks_limit_size 32
         retry_forever true
       </buffer>
       log_group_name /aws/eks/<cluster_name>/cluster/namespace/default
    </match>
```

**Comment by ws-prive** [comment]
Hi @Cryptophobia,

Thanks again!
