### ISSUE TITLE
`log-router` chart not published as a release asset

### ISSUE THREAD

**Issue by gg-kialo** [vmware/kube-fluentd-operator#323]
### Describe the bug

The [log-router-0.4.0.tgz](https://github.com/vmware/kube-fluentd-operator/releases/download/v1.16.2/log-router-0.4.0.tgz) has not been published as part of releases since v1.16.3. The README.md has been updated to point to one included in the v1.16.3 release (In the [Try it out](https://github.com/vmware/kube-fluentd-operator#try-it-out) section, but there's nothing at that link.

### Reproduction steps

```bash
Follow the instructions in the [Try it out](https://github.com/vmware/kube-fluentd-operator#try-it-out) section.

Helm fails while installing the chart:


Error: INSTALLATION FAILED: failed to download "https://github.com/vmware/kube-fluentd-operator/releases/download/v1.16.3/log-router-0.4.0.tgz"
```
```


### Expected behavior

The chart is successfully installed.

### Additional context

_No response_

**Comment by BriceLag** [comment]
Hello @javiercri,
Thank you for your job.
After reading the readme, we have the same problem as @gg-kialo, but on the version 1.16.6.
The URL: 'https://github.com/vmware/kube-fluentd-operator/releases/download/v1.16.6/log-router-0.4.0.tgz'
is not working.
The last log-router-0.4.0.tgz downloadable is the version under the v1.16.2.
Can you create the chart or update the documentation?
Best regards,

Brice

**Comment by berlin-ab** [comment]
This pull request seems to be a solution to this problem:

https://github.com/vmware/kube-fluentd-operator/pull/330

What can be done to move it forward?

**Comment by javiercri** [comment]
Fixed!

**Comment by BriceLag** [comment]
Thank you all for your work!
I've tried to download the version: https://github.com/vmware/kube-fluentd-operator/releases/download/v1.16.7/log-router-0.4.0.tgz, explained in the [Readme](https://github.com/vmware/kube-fluentd-operator#readme) and the download doesn't work. But that will work for the next version ?
Best regards,
