### ISSUE TITLE
jvassev/kube-fluentd-operator:v1.7.0 is missing

### ISSUE THREAD

**Issue by sermilrod** [vmware/kube-fluentd-operator#35]
Documentation to install the operator points to use v1.7.0 but there is no docker image available. I have to choose latest or v1.6.0.

Can you push the image please? There is no documentation in Docker Hub either about how the image got built. A link to the Dockerfile will be also good.

**Comment by jvassev** [comment]
Thanks for pointing this out. I've pushed `v1.7.0` tag to Docker hub.
The Dockerfile itself cannot be linked as the image push is not automated but performed by a CI job.
Nevertheless, I've linked the project's github page

**Comment by sermilrod** [comment]
Thank you very much!
