### ISSUE TITLE
We are seeing log delay/missing on KFO

### ISSUE THREAD

**Issue by yuzs2** [vmware/kube-fluentd-operator#375]
### Describe the bug

We are using KFO 1.16.7 to collect the logs in our k8s cluster and forward the logs to LogInsight. However, we can see:
1. some logs are missing in LogInsight, we can see the logs when using `kubectl logs`, but can not see the logs in LosInsght. We have confirmed that the LogInsght is not dropping logs, the issue points to KFO. 
3. we can also see log ingestion delay in LogInsight, the delay even could be hours.

### Reproduction steps

The log missing/delay issue happens on all of our clusters, especially when a cluster is having a higher workload, but we can confirm that LogInsight is not dropping logs. We can provide the KFO logs if needed.

### Expected behavior

We should not see logs missing/delay in KFO

**Comment by slimm609** [comment]
we have made several updates in the latest versions to improve this.

**Comment by slimm609** [comment]
This was related to the max read bytes.  This has been increased in 1.18 and also now has a flag to increase this more on busy systems
