### ISSUE TITLE
Support multi-valued tags

### ISSUE THREAD

**Issue by jvassev** [vmware/kube-fluentd-operator#4]
Currently, to keep parser code simple this is not possible:
```xml
<match a b>
</match>
```

Users need to split their tag into two directives:
```xml
<match a>
</match>

<match b>
</match>
```

The usual space-delimited multi-valued tags should be supported too.

**Comment by carpenterm** [comment]
Fixed in https://github.com/vmware/kube-fluentd-operator/pull/87
