### ISSUE TITLE
Multiprocess Input Plugin support

### ISSUE THREAD

**Issue by HarishHothi** [vmware/kube-fluentd-operator#47]
Hi,
   @jvassev Do you think adding [multiprocess](https://docs.fluentd.org/v0.10/articles/in_multiprocess) support will be good addition?
   By default fluentd uses single cpu and multiprocess input plugin is recommended for [performance-tuning](https://docs.fluentd.org/v0.10/articles/performance-tuning) .

**Comment by jvassev** [comment]
Hi @HarishHothi,

It seems Multiprocess has been superseded by Workers (https://docs.fluentd.org/v1.0/articles/multi-process-workers)
However, Workers needs to be handled with care because some plugins require specific configuration when used with workers.

**Comment by HarishHothi** [comment]
Thank you @jvassev I will look into it :) , Currently base image points fluentd v1.2.6, any near plans to update it to latest version?
