### ISSUE TITLE
Update fluentd Image 

### ISSUE THREAD

**Issue by HarishHothi** [vmware/kube-fluentd-operator#50]
Hi @jvassev  Fluentd released its 1.4.2 version. Kube-fluentd operator also should be updated with 1.4.2 fluentd version.

**Comment by jvassev** [comment]
This is scheduled for the next minor release. We'd like users to migrate to 1.10 and adopt the now built-in `parser` plugin first.

**Comment by james-crowley** [comment]
@jvassev I see you are preparing for release `1.9.0`, is this going to include the update to Fluentd `1.4.2`? Or is that intended for `1.10`?

I ask cause multiarch support for Fluentd is only support on `1.4` and up. I would like to get this operator to run natively on `s390x` without any modifications, but in order to do so we need to pull from the multiarch image. Here is the link to the docker hub, https://hub.docker.com/_/fluentd.

**Comment by james-crowley** [comment]
I also discovered that the `fluent-plugin-google-cloud` seems to require Fluentd `1.4.2`. Here is the [link](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/509af56b5c614b887ad3ebfe24c2409706b602fa/fluent-plugin-google-cloud.gemspec#L22). I am still pretty new to Fluentd and Ruby but it seems like it says its requiring Fluentd runtime of `1.4.2`.

**Comment by jvassev** [comment]
1.9.0 will be the last release with fluent 1.2. 1.10 will handle the upgrade to latest fluentd and any issues it may bring.

**Comment by james-crowley** [comment]
@jvassev Do you have an ETA when v1.10 will be ready? Also, is there anything I can do to help with testing v1.10.0? Fork and try out Fluentd 1.4.2?

**Comment by james-crowley** [comment]
@jvassev In the meantime, would you mind commenting on this issue, https://github.com/fluent/fluentd-docker-image/issues/189. Maybe with a comment from you, we could gain some more traction to get Fluentd 1.2.6 a multi-arch release.

**Comment by jvassev** [comment]
Hi all,
I've upgraded fluentd to 1.5.2. This required also a small change to the helm chart.
Can you try running with `jvassev/kube-fluentd-operator:v1.9.0-13-g2516f56` and with the new helm chart?
Only the vertica has been removed as it fails to compile with the new Ruby version.

**Comment by jvassev** [comment]
I've added a Gemfile to pin the fluentd version and ensure the latest compatible plugin get installed during build.

I am planning to release 1.10.0 with fluentd-1.5.2 support this weekend and target 1.6.x for the next release.
