### ISSUE TITLE
Add fluent-plugin-bufferize plugin

### ISSUE THREAD

**Issue by vsakarov** [vmware/kube-fluentd-operator#57]
Currently if you use https://github.com/toshitanian/fluent-plugin-out-http-ext there is no mechanism for retrying and failed requests. fluent-plugin-bufferize is the helper plugin to achieve this functionality.

P.S. fluent-plugin-out-http-ext is deprecated, so you might think of adding https://github.com/fluent-plugins-nursery/fluent-plugin-out-http .

**Comment by jvassev** [comment]
Thanks for the deprecation notice.
The old plugin `fluent-plugin-out-http-ext (0.1.10)`  is now replaced with `fluent-plugin-out-http (1.3.1)`
