### ISSUE TITLE
Support custom SSL certificates

### ISSUE THREAD

**Issue by sneko** [vmware/kube-fluentd-operator#6]
Hi!

It would be great if we could define volumes through Helm chart.

For example I'm using this fluentd configuration to send logs to Elasticsearch cluster over HTTPS connection:
```
...
  ssl_version TLSv1_2
  ca_file "/.../ca.crt"
  client_key "/.../es01.key"
  client_cert "/.../es01.crt"
```

These files are stored in a ConfigMap, may the chart could leave the possibility to specify a ConfigMap name, and if it exists, mount the volume?

Thanks

**Comment by jvassev** [comment]
@Sneko Elasticsearch's helm chart is really easy to extend - thanks for pointing out their solution!

Would you like to contribute it? We should have this for sure for 1.2.0 release, but now I am focused on log-stream sharing (#3).

Thanks,
Julian

**Comment by sneko** [comment]
@jvassev by "extending" their chart, are you referencing to any sort of inheritance (like subchart...)?

Or you were asking me to add appropriate fields in your .yaml files?

Thanks

**Comment by jvassev** [comment]
I think copying the relevant bit is fine. As our chart is in no way related to the `incubator/fluentd-elasticsearch` the only option is to use the same approach. It's hard to reuse code in Helm anyway.

**Comment by sneko** [comment]
#7
