### ISSUE TITLE
Plugin macros does not preserve defined buffer configuration

### ISSUE THREAD

**Issue by davydkov** [vmware/kube-fluentd-operator#62]
I have defined macros in kube-system:

```
<plugin elastic>
  @type elasticsearch
  host elastic-nodes
  port 9200
  <buffer>
     @type file
     path /var/log/fluentd.*.buffer
  </buffer>      
</plugin>
```

in namespaces
```
<match **>
   @type elastic
</match>
```

Generated config is
```
<match kube.namespace.*.*._labels.>
  @type elasticsearch
  host elastic-nodes
  port 9200
</match>
```
I expect that macros keeps buffer configuration

**Comment by jvassev** [comment]
Hi @davydkov,

Thanks for reporting this issue! It's a bug - no nested content was ever expanded when using `<plugin>`.
This is the fix: https://github.com/vmware/kube-fluentd-operator/commit/76a21809707ab7ff1697552386729e6993d70836

You can verify the fix by upgrading to this pre-release image `jvassev/kube-fluentd-operator:v1.9.0-2-g76a2180`

**Comment by davydkov** [comment]
Verified! Thanks
This issue can be closed
