### ISSUE TITLE
Unknown filter plugin `parse`

### ISSUE THREAD

**Issue by uipo78** [vmware/kube-fluentd-operator#66]
For any of the examples in the documentation with `@type parse`, the `reloader` logs show this message:
```
error_class=Fluent::ConfigError error="Unknown filter plugin 'parse'. Run 'gem search -rd fluent-plugin' to find plugins"
```

One of the examples from the documentation:
```
<filter $labels(server=apache)>
  @type parse
  <parse>
    @type apache2
  </parse>
</filter>

<filter $labels(app=django)>
  @type detect_exceptions
  language python
</filter>

<match **>
  @type es
</match>
```

Any idea why that error hasn't shown up for you all?

**Comment by uipo78** [comment]
I should've read the changelog for v1.9.0, doh. `@type parse` is no longer a thing.

Hopefully no one makes the mistake that I just made!

**Comment by jvassev** [comment]
Thanks for pointing this out. I need to fix the README too.
