### ISSUE TITLE
libjemalloc Arch Issue and Installed Already

### ISSUE THREAD

**Issue by james-crowley** [vmware/kube-fluentd-operator#69]
I am working on porting this Helm Chart and the respective Docker containers to s390x. I noticed in the Docker container you set `ENV LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libjemalloc.so.1"`. This would not work for s390x since the path is slightly different, `ENV LD_PRELOAD="/usr/lib/s390x-linux-gnu/libjemalloc.so.1"`. It is a small change to make and not a huge issue, but I am a little confused why you guys are install libjemalloc again?

Looking at the Dockefile you guys are pulling from, `fluent/fluentd:v1.2.6-debian`, you can see that they are already installing libjemalloc. 

Here is the snip it:

```
 && wget -O /tmp/jemalloc-4.5.0.tar.bz2 https://github.com/jemalloc/jemalloc/releases/download/4.5.0/jemalloc-4.5.0.tar.bz2 \
 && cd /tmp && tar -xjf jemalloc-4.5.0.tar.bz2 && cd jemalloc-4.5.0/ \
 && ./configure && make \
 && mv lib/libjemalloc.so.2 /usr/lib \
```

From the looks of it, they are actually pulling in a newer version of libjemalloc that you can find via apt. 

```
root@cfe3103b08f8:/usr/lib# apt search libjemalloc1
Sorting... Done
Full Text Search... Done
libjemalloc1/oldstable 3.6.0-9.1 s390x
  general-purpose scalable concurrent malloc(3) implementation

libjemalloc1-dbg/oldstable 3.6.0-9.1 s390x
  debug symbols for jemalloc
```

I am still pretty new to this project and still trying to figure things out, so please correct me if I am wrong. Is it that your application needs this version of libjemalloc you can get via apt?

Additionally, if the apt version is required could you add a small fix to make it arch agnostic? The Docker container your pulling from again, uses this snip it to achieve this by moving libjemalloc to `/usr/lib` not `/usr/lib/ARCH/`. Then export `ENV LD_PRELOAD="/usr/lib/libjemalloc.so.1"`

**Comment by jvassev** [comment]
Hi,
The current Dockeril pulls libjmalloc from apt.
I see I've left a pointer to this in the dockerfile: https://packages.debian.org/stretch/amd64/libjemalloc1/filelist

When you say you are porting to s390x, do you mean changing the base image from debian to something else? If so, you can also change the LD_.. line as part of the port.

**Comment by james-crowley** [comment]
@jvassev As for porting, I built the base image of `fluentd:v1.2.6-debian` since it does not have s390x in the manifest. Now I need to make sure your container works on s390x.


One of the issues, as I mentioned, is the `LD_PRELOAD` path. Why are you install libjmalloc again, if the base image already has it installed?

**Comment by james-crowley** [comment]
After some testing, I found that the install of libjmalloc via apt is unneeded. In my test I removed the package from the list of packages to install. Additionally, I removed the exporting of `LD_PRELOAD` sense the base images already includes the export pointing to the version of libjmalloc they installed. 

@jvassev I am not sure why you need to install another version of libjmalloc and export `LD_PRELOAD`, when your container runs fine without it.

**Comment by jvassev** [comment]
You are right the base image contains a pinned version of jemalloc. Let's use what's in the base fluent image.
Can you submit a PR that deletes the package installation and customizing the LD_.. ?

**Comment by james-crowley** [comment]
@jvassev Just submitted the PR.
