### ISSUE TITLE
Error on startup v1.10.0

### ISSUE THREAD

**Issue by uipo78** [vmware/kube-fluentd-operator#74]
When I deploy the fluentd-operator to my cluster, I receive this error:

```
time="2019-09-13T15:57:57Z" level=fatal msg="Bad validate command used: '/usr/local/bin/fluentd -p /fluentd/plugins', either use correct one or none at all: invalid fluentd binary used /usr/local/bin/fluentd: fork/exec /usr/local/bin/fluentd: no such file or directory"
```

Not entirely sure of the source of this problem.

**Comment by rjackson90** [comment]
I experienced this error while I was messing around with the operator. In my case, I tried to use a chart version which was too old. Upgrading to `1.10.0` fixed it for me. I don't pin the version of the container being used, and the chart defaults to `latest`. So if you don't want to upgrade your chart version you could try pinning to an older container image by specifying the following in your Helm values override file: 

```
image:
  repository: jvassev/kube-fluentd-operator
  tag: v1.8.0
```

you should choose the value of `tag` to be compatible with the version of the chart you are using.

**Comment by jvassev** [comment]
@uipo78 My bad, I forgot to mention this change in the changelog: https://github.com/vmware/kube-fluentd-operator/commit/2516f56b0d78691ce949b0952a699f861509d909

For 1.10 and above the upgraded helm chart must be used: https://github.com/vmware/kube-fluentd-operator/releases/download/v1.10.0/log-router-0.3.2.tgz
