### ISSUE TITLE
helm install fails

### ISSUE THREAD

**Issue by anothersrewhocancode** [vmware/kube-fluentd-operator#95]
[centos@ip-172-31-4-30 ~]$ 
```
helm install --name kfo ./kube-fluentd-operator/log-router \
>   --set rbac.create=true \
>   --set image.tag=v1.11.0 \
>   --set image.repository=jvassev/kube-fluentd-operator
```

> Error: release kfo failed: DaemonSet.apps "kfo-log-router" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"log-router", "release":"kfo"}: `selector` does not match template `labels

any reason why i get this error.
how can i fix this.

Thanks any help would be appreciated.

**Comment by jvassev** [comment]
Hi, this MR https://github.com/vmware/kube-fluentd-operator/pull/94 fixes the helm chart.
