### ISSUE TITLE
Update of fluent-plugin-google-cloud?

### ISSUE THREAD

**Issue by sneko** [vmware/kube-fluentd-operator#96]
Hi,

`fluent-plugin-google-cloud` seems really outdated and I was wondering if you could update it? I got some troubles using it (https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/364). I see the Gemfile in the repository but I guess the version is specified inside the Gemfile.lock that was not committed, right?

Your README.md indeed says the version of this plugin is 0.4.10, note the current latest version is 0.7.27

Thank you,

**Comment by sneko** [comment]
A the end I patched the image as I can.

````
FROM jvassev/kube-fluentd-operator:v1.11.0

# Update system
RUN gem install fluent-plugin-google-cloud -v 0.7.27 && \
    gem cleanup
```

I'm not totally satisfied using `gem` over `bundle update` but it was always complaining about other dependencies... 😢 the docker seems to run properly.

But I'm still not able to get logs into Stackdriver, and even by putting log level as DEBUG it's not really helpful I just get:
`Configuration for namespace XXXXX cannot be validated with fluentd`

And my config for the namespace XXXXX is just:
```
<match **>
  @type google_cloud
</match>
```

It drives me crazy... Any would be appreciated 👍

**Comment by sneko** [comment]
As explained in the README.md, it seems when configuring `kube-system` it works since no process in made on the file, compared to other namespaces...

I don't know how the schema is parsed for plugins.
https://github.com/vmware/kube-fluentd-operator/blob/master/config-reloader/generator/generator.go#L189-L202

I could set an empty value for `cfg.FluentdValidateCommand` so no validator if created. But it seems a patch over a patch. Will wait for an advice.

**Comment by jvassev** [comment]
Hi @sneko ,
Unfortunately the gem spec for the google_cloud plugins requires a very specific version of fluentd: https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/master/fluent-plugin-google-cloud.gemspec#L22. It may work on multiple version though.

Compare this to the cloudwatch plugin which declares it can works with multiple versions: https://github.com/fluent-plugins-nursery/fluent-plugin-cloudwatch-logs/blob/master/fluent-plugin-cloudwatch-logs.gemspec#L20

So you have done the only thing that could work: build a custom image "forcing" a new version. Declarative dependency resolution won't work as the metadata for the google_cloud is very strict. I tried `gem 'fluent-plugin-google-cloud', '>=0.7.27'` and it got (rightfully so) rejected.

Also, for the next version of operator, 1.12.0, where fluentd will be bumped to 1.7.0, the same trick needs to be done again unless the plugin's spec is fixed.

Btw, the only reason the google_plugin gets installed at all is this old gemspec which make it compatible with future fluentd releases:
https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/v0.4.10/fluent-plugin-google-cloud.gemspec#L21

In this case, if the google_plugin is not changed to accept a version range then I will have to force the latest version as part of this project:)

**Comment by sneko** [comment]
@jvassev thank you for the detailed answer!

I just pinged them on my issue on their repo, maybe this can be fixed 😃
