### ISSUE TITLE
Does not match for labels containing .

### ISSUE THREAD

**Issue by cw-sakamoto** [vmware/kube-fluentd-operator#98]
I want to log epoxrt the following application(external-dns), but because of the dot in the label, it cannot be matched well. Is there any better way than adding a label without dots?
https://github.com/helm/charts/blob/master/stable/external-dns/templates/_helpers.tpl#L35-L40

**Comment by viveksyngh** [comment]
@cw-sakamoto have you tried using `.` in the label names and what error are you getting ? I can see that it considers label with `.` as a valid label

https://github.com/vmware/kube-fluentd-operator/blob/7f7a27702d2411f492b6dec35b7c42a1ea93034b/config-reloader/processors/labels.go#L36

**Comment by Cryptophobia** [comment]
Regex was correct but the whenever the label has a period ( . ), the validation dropped the key. I think the PR #201 will finally fix.
